---
abstract: 'Sugar for your favorite ORM, DBIx::Class'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Candy
requires:
  DBIx::Class: 0.08123
  Lingua::EN::Inflect: 0
  MRO::Compat: 0.11
  String::CamelCase: 0
  Sub::Exporter: 0.982
  Test::Deep: 0
  Test::Fatal: 0
  Test::More: 0.94
  namespace::clean: 0.18
resources:
  repository: git://github.com/frioux/DBIx-Class-Candy.git
version: 0.002102
